version: '3'
services:
  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    environment:
      API_NAME: iGP Auth
      API_PORT: 3000
      API_ENV: development
      API_PREFIX: api
      DATABASE_URL: mongodb://mongodb:27017/igp-auth
      LOG_LEVEL: error
      JWT_SECRET: fh7sd89fHs412nojADsdaaE45
      JWT_EXPIRY: 30

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
